#! /usr/bin/env bash

export NODE_NO_WARNINGS=1

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ARGS=()
for arg in "$@"; do
  case "$arg" in
    -m|--main) export ELV_NET="main" ;;
    -d|--dv3|--demov3) export ELV_NET="demov3" ;;
    --test) export ELV_NET="test" ;;
    --dev) export ELV_NET="dev" ;;
    *) ARGS+=("$arg") ;;
  esac
done

if [ -e $SOURCE_DIR/utilities/EluvioLiveCli.js ]
then
  exec node $SOURCE_DIR/utilities/EluvioLiveCli.js "${ARGS[@]}" 2>&1
elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli.js ]
then
  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli.js "${ARGS[@]}" 2>&1
else
  echo "(elv-live-js) cannot find utilities/EluvioLiveCli.js" 1>&2
  exit 1
fi
