#! /usr/bin/env bash

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


if [ -e $SOURCE_DIR/utilities/EluvioMediaWalletCli.js ]
then
  exec node $SOURCE_DIR/utilities/EluvioMediaWalletCli.js "$@" 2>&1
elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioMediaWalletCli.js ]
then
  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioMediaWalletCli.js "$@" 2>&1
else
  echo "(elv-live-js) cannot find utilities/EluvioMediaWalletCli.js" 1>&2
  exit 1
fi